<a href="https://colab.research.google.com/github/MehdiQurbanov/Annotation-Processor/blob/main/Loss_Cost_Functions_in_Deep_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import numpy as np

In [24]:
y_predicted = np.array([1,1,0,0,1])
y_true = np.array([0.30,0.7,1,0,0.5])

Implement Mean Absolute Error

In [25]:
def mae(y_predicted, y_true):
    total_error = 0
    for yp, yt in zip(y_predicted, y_true):
        total_error += abs(yp - yt)
    print("Total error is:",total_error)
    mae = total_error/len(y_predicted)
    print("Mean absolute error is:",mae)
    return mae

In [26]:
mae(y_predicted, y_true)

Total error is: 2.5
Mean absolute error is: 0.5


np.float64(0.5)

Implement same thing using numpy in much easier way

In [27]:
np.abs(y_predicted-y_true)

array([0.7, 0.3, 1. , 0. , 0.5])

In [28]:
np.mean(np.abs(y_predicted-y_true))

np.float64(0.5)

In [29]:
def mae_np(y_predicted, y_true):
    return np.mean(np.abs(y_predicted-y_true))

In [30]:
mae_np(y_predicted, y_true)

np.float64(0.5)

Implement Log Loss or Binary Cross Entropy

In [31]:
np.log([0])

/tmp/ipython-input-262464415.py:1: RuntimeWarning: divide by zero encountered in log
  np.log([0])


array([-inf])

In [33]:
epsilon = 1e-15

In [34]:
np.log([1e-15])

array([-34.53877639])

In [35]:
y_predicted

array([1, 1, 0, 0, 1])

In [36]:
y_predicted_new = [max(i,epsilon) for i in y_predicted]
y_predicted_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [37]:
1-epsilon

0.999999999999999

In [38]:
y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
y_predicted_new

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [39]:
y_predicted_new = np.array(y_predicted_new)

In [40]:
np.log(y_predicted_new)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [41]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

np.float64(17.2696280766844)

In [42]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [43]:
log_loss(y_true, y_predicted)

np.float64(17.2696280766844)